# Generated by Django 2.0.3 on 2018-05-16 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='telegram user id')),
                ('date_of_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of create')),
                ('favorite_color', models.CharField(blank=True, default='', max_length=35, verbose_name='word')),
                ('age', models.IntegerField(default=0, verbose_name='telegram user id')),
            ],
            options={
                'db_table': 'bot1_telegram_user',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec', models.CharField(default='', max_length=40, verbose_name='word')),
                ('pt', models.CharField(default='', max_length=20, verbose_name='Partofspeech')),
                ('sem', models.CharField(default='', max_length=41, verbose_name='wordnumber')),
                ('st1', models.CharField(default='nil', max_length=60, verbose_name='sort1')),
                ('st2', models.CharField(default='nil', max_length=60, verbose_name='sort2')),
                ('st3', models.CharField(default='nil', max_length=60, verbose_name='sort3')),
                ('comment', models.CharField(default='nil', max_length=100, verbose_name='comment')),
            ],
            options={
                'db_table': 'bot1_telegram_word',
            },
        ),
    ]
